;this file for FamiTone4.0 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


blockDude_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; MainMenu
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,245,204 ; PreLevel
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Level
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; GameOver
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256 ; FanFare

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env0,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$c7,$c8,$c9,$c9,$c7,$c6,$c5,$c5,$c4,$c3,$c3,$00,$0b


; MainMenu
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$1c,$00,$83,$23,$00,$83,$1c,$00,$83,$23,$00,$83,$1c,$00,$83
	.byte $23,$00,$1c,$00,$83,$1c,$00,$23,$00,$83
@ref1:
	.byte $1c,$00,$83,$23,$00,$83,$1c,$00,$83,$23,$00,$83,$1c,$00,$83,$23
	.byte $00,$1c,$00,$83,$1c,$00,$23,$00,$83
@ref2:
	.byte $20,$00,$83,$23,$00,$83,$20,$00,$83,$23,$00,$83,$20,$00,$83,$23
	.byte $00,$20,$00,$83,$20,$00,$23,$00,$83
@ref3:
	.byte $21,$00,$83,$23,$00,$83,$21,$00,$83,$23,$00,$83,$21,$00,$83,$23
	.byte $00,$21,$00,$87,$23,$00,$83
	.byte $ff,$19
	.word @ref1
	.byte $ff,$19
	.word @ref1
	.byte $ff,$19
	.word @ref2
	.byte $ff,$17
	.word @ref3
	.byte $ff,$19
	.word @ref1
	.byte $ff,$19
	.word @ref1
	.byte $ff,$19
	.word @ref2
	.byte $ff,$17
	.word @ref3
	.byte $fd
	.word @song0ch0loop

; MainMenu
@song0ch1:
@song0ch1loop:
@ref12:
	.byte $83,$80,$28,$81,$2c,$81,$28,$81,$2f,$81,$28,$81,$2c,$81,$28,$00
	.byte $83,$28,$81,$2c,$81,$28,$81,$2f,$81,$28,$81,$2c,$81,$28,$00
@ref13:
	.byte $83,$28,$81,$2c,$81,$28,$81,$2f,$81,$28,$81,$2c,$81,$28,$00,$83
	.byte $28,$81,$2c,$81,$28,$81,$2f,$81,$28,$81,$2c,$81,$28,$00
	.byte $ff,$1e
	.word @ref13
	.byte $ff,$1e
	.word @ref13
	.byte $ff,$1e
	.word @ref13
	.byte $ff,$1e
	.word @ref13
	.byte $ff,$1e
	.word @ref13
	.byte $ff,$1e
	.word @ref13
@ref20:
	.byte $83,$2f,$00,$2f,$00,$2c,$00,$2c,$00,$2a,$00,$2a,$00,$28,$00,$83
	.byte $2f,$00,$2f,$00,$2c,$00,$2c,$00,$2a,$00,$2a,$00,$28,$00
	.byte $ff,$1e
	.word @ref20
@ref22:
	.byte $83,$6b,$01,$28,$85,$00,$81,$6b,$00,$2c,$2d,$2c,$2d,$2c,$85,$00
	.byte $81,$6b,$01,$28,$85,$00,$81,$6b,$00,$2c,$81,$00,$85,$31,$00
@ref23:
	.byte $31,$00,$2f,$00,$2f,$00,$2d,$00,$2d,$00,$2c,$00,$2c,$00,$2a,$00
	.byte $2d,$00,$2f,$00,$2d,$00,$2c,$00,$2a,$00,$2c,$00,$2a,$00,$28,$00
	.byte $fd
	.word @song0ch1loop

; MainMenu
@song0ch2:
@song0ch2loop:
@ref24:
	.byte $80,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c
	.byte $00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c
	.byte $00
@ref25:
	.byte $1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00
	.byte $1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00,$1c,$00
@ref26:
	.byte $20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00
	.byte $20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00,$20,$00
@ref27:
	.byte $21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00
	.byte $21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00,$21,$00
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref27
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref27
	.byte $fd
	.word @song0ch2loop

; MainMenu
@song0ch3:
@song0ch3loop:
@ref36:
	.byte $82,$10,$82,$00,$83,$0d,$00,$10,$00,$83,$10,$00,$0d,$00,$83,$10
	.byte $00,$83,$0d,$00,$10,$00,$83,$10,$00,$0d,$00,$83
@ref37:
	.byte $10,$00,$83,$0d,$00,$10,$00,$83,$10,$00,$0d,$00,$83,$10,$00,$83
	.byte $0d,$00,$10,$00,$83,$10,$00,$0d,$00,$83
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$1a
	.word @ref37
	.byte $fd
	.word @song0ch3loop

; MainMenu
@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; PreLevel
@song1ch0:
	.byte $fb,$06
@ref60:
	.byte $80,$28,$00,$83,$28,$00,$28,$85,$00,$81,$2a,$00,$83,$28,$00,$83
	.byte $2a,$00,$83,$2c,$8d,$6c,$04,$8f,$6b,$00,$2c,$00
@song1ch0loop:
@ref61:
	.byte $81
	.byte $fd
	.word @song1ch0loop

; PreLevel
@song1ch1:
@ref62:
	.byte $80,$23,$00,$83,$23,$00,$23,$85,$00,$81,$21,$00,$83,$23,$00,$83
	.byte $25,$00,$83,$1c,$8d,$6b,$04,$8f,$6b,$00,$1c,$00
@song1ch1loop:
@ref63:
	.byte $81
	.byte $fd
	.word @song1ch1loop

; PreLevel
@song1ch2:
@ref64:
	.byte $80,$2c,$95,$2a,$85,$2c,$85,$2d,$85,$2f,$9f,$00
@song1ch2loop:
@ref65:
	.byte $81
	.byte $fd
	.word @song1ch2loop

; PreLevel
@song1ch3:
@ref66:
	.byte $d3
@song1ch3loop:
@ref67:
	.byte $81
	.byte $fd
	.word @song1ch3loop

; PreLevel
@song1ch4:
@ref68:
	.byte $d3
@song1ch4loop:
@ref69:
	.byte $81
	.byte $fd
	.word @song1ch4loop


; Level
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref70:
	.byte $80,$2c,$85,$28,$89,$2a,$89
@ref71:
	.byte $25,$00,$87,$25,$00,$83,$23,$00,$87
@ref72:
	.byte $2c,$85,$28,$89,$2a,$89
	.byte $ff,$09
	.word @ref71
@ref74:
	.byte $2d,$85,$2a,$00,$8b,$28,$85
@ref75:
	.byte $25,$00,$9b
	.byte $ff,$07
	.word @ref74
@ref77:
	.byte $2c,$00,$2c,$00,$2c,$00,$2c,$00,$2f,$00,$2f,$00,$2f,$00,$2f,$00
	.byte $fd
	.word @song2ch0loop

; Level
@song2ch1:
@song2ch1loop:
@ref78:
	.byte $80,$1c,$00,$20,$00,$1c,$00,$20,$91
@ref79:
	.byte $1c,$00,$87,$21,$00,$83,$20,$00,$87
@ref80:
	.byte $21,$00,$23,$00,$21,$00,$23,$91
	.byte $ff,$09
	.word @ref79
@ref82:
	.byte $83,$25,$00,$25,$8d,$23,$85
@ref83:
	.byte $1e,$00,$9b
	.byte $ff,$07
	.word @ref82
@ref85:
	.byte $87,$6b,$04,$8b,$6b,$00,$2f,$89
	.byte $fd
	.word @song2ch1loop

; Level
@song2ch2:
@song2ch2loop:
@ref86:
	.byte $80,$28,$00,$28,$00,$83,$2c,$91
@ref87:
	.byte $25,$00,$87,$25,$00,$8f
@ref88:
	.byte $28,$00,$28,$00,$83,$2c,$91
	.byte $ff,$06
	.word @ref87
@ref90:
	.byte $2a,$00,$2a,$00,$2a,$00,$2a,$00,$2a,$00,$2a,$00,$2c,$00,$2c,$00
@ref91:
	.byte $2d,$00,$2d,$00,$2d,$00,$2d,$00,$2d,$00,$2d,$00,$2d,$00,$2d,$00
	.byte $ff,$10
	.word @ref90
@ref93:
	.byte $2f,$00,$2f,$00,$2f,$00,$2f,$00,$2f,$00,$2f,$00,$2d,$00,$2c,$00
	.byte $fd
	.word @song2ch2loop

; Level
@song2ch3:
@song2ch3loop:
@ref94:
	.byte $80,$10,$00,$83,$0d,$00,$10,$00,$83,$10,$00,$0d,$00,$83
	.byte $ff,$0d
	.word @ref94
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$0d
	.word @ref37
	.byte $fd
	.word @song2ch3loop

; Level
@song2ch4:
@song2ch4loop:
@ref102:
	.byte $9f
@ref103:
	.byte $9f
@ref104:
	.byte $9f
@ref105:
	.byte $9f
@ref106:
	.byte $9f
@ref107:
	.byte $9f
@ref108:
	.byte $9f
@ref109:
	.byte $9f
	.byte $fd
	.word @song2ch4loop


; GameOver
@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref110:
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $fd
	.word @song3ch0loop

; GameOver
@song3ch1:
@song3ch1loop:
	.byte $ff,$07
	.word @ref110
	.byte $fd
	.word @song3ch1loop

; GameOver
@song3ch2:
@song3ch2loop:
@ref112:
	.byte $81,$81,$81,$81,$81,$81,$81
	.byte $fd
	.word @song3ch2loop

; GameOver
@song3ch3:
@song3ch3loop:
	.byte $ff,$07
	.word @ref110
	.byte $fd
	.word @song3ch3loop

; GameOver
@song3ch4:
@song3ch4loop:
	.byte $ff,$07
	.word @ref112
	.byte $fd
	.word @song3ch4loop


; FanFare
@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref115:
	.byte $70,$81
	.byte $fd
	.word @song4ch0loop

; FanFare
@song4ch1:
@song4ch1loop:
@ref116:
	.byte $70,$81
	.byte $fd
	.word @song4ch1loop

; FanFare
@song4ch2:
@song4ch2loop:
@ref117:
	.byte $81
	.byte $fd
	.word @song4ch2loop

; FanFare
@song4ch3:
@song4ch3loop:
@ref118:
	.byte $70,$81
	.byte $fd
	.word @song4ch3loop

; FanFare
@song4ch4:
@song4ch4loop:
@ref119:
	.byte $81
	.byte $fd
	.word @song4ch4loop
